bifrost-platform/bifrost-node

src/join_validators.ts, src/set_session_keys.ts
=> chore: Exit process when node endpoint not reachable

.dockerignore, maintenance/alertmanager/alertmanager.yml, maintenance/docker-compose.yml, maintenance/grafana/grafana.ini, maintenance/prometheus/prometheus.yml, maintenance/prometheus/rules.yml
Grafana + Mariadb + Prometheus + node_exporter + alertmanger monitoring stack docker-compose file
=> deploy: monitoring stack

pallets/bfc-utility/src/lib.rs, pallets/bfc-utility/src/pallet/mod.rs, pallets/bfc-utility/src/weights.rs, runtime/dev/src/lib.rs, runtime/testnet/src/lib.rs
Add permissioned native token mint extrinsic to pallet_bfc_utility
=> add permissioned native token mint extrinsic

Cargo.lock, node/core/Cargo.toml, tests/package-lock.json, tests/package.json, tools/package-lock.json, tools/package.json
This PR contains a minor bug on the frontier implementation.
Related [issue](https://github.com/bifrost-platform/bifrost-frontier/pull/1)
=> release bifrost-node v1.2.1

tools/README.md, tools/package-lock.json, tools/package.json, tools/src/join_validators.ts, tools/src/query/query_events.ts, tools/src/query/query_extrinsic.ts, tools/src/query/query_extrinsics.ts, tools/src/set_session_keys.ts
- Add data query CLI tools
- `query_extrinsics`
- `query_events`
- `query_extrinsic`
=> NODE-32, feature: query CLI

maintenance/alertmanager/alertmanager.yml, maintenance/docker-compose.yml, maintenance/prometheus/prometheus.yml
- `docker-compose.yml` 파일에 prometheus port export
=> chore: update maintenance configs

runtime/mainnet/src/lib.rs
- increase the minimum deposit amount required to submit a proposal (mainnet only)
- 100 BFC -> 20,000 BFC
=> NODE-46, feature: increase proposal minimum deposit

tools/README.md, tools/package.json, tools/src/transfer.ts
- Support CLI for simple transfers.
- Update tools README
=> NODE-54, feature: support simple transfer CLI

Cargo.lock, Cargo.toml, node/common/Cargo.toml, node/common/src/tracing.rs, node/dev/src/service.rs, node/mainnet/src/service.rs, node/testnet/src/service.rs, runtime/testnet/src/lib.rs
This PR will resolve ethapi bug
=> fix: apply ethapi bugfix updates from frontier

tests/.gitignore, tests/package.json, tests/runtime/config.default.json, tests/runtime/test_client_upgrade.ts
- client upgrade에 대응하기 위한 테스트 코드 작성
=> NODE-62, tests: add test codes for client upgrades

rust-toolchain.toml
Resolve [CVE-2023-38497](https://github.com/advisories/GHSA-j3xp-wfr4-hx87.).
=> Resolve CVE-2023-38497

Cargo.lock, Cargo.toml, node/core/Cargo.toml, pallets/bfc-offences/src/lib.rs, pallets/bfc-offences/src/pallet/mod.rs, pallets/bfc-staking/src/inflation.rs, pallets/bfc-staking/src/lib.rs, pallets/bfc-staking/src/pallet/impls.rs, pallets/bfc-staking/src/pallet/mod.rs, pallets/bfc-utility/src/lib.rs, pallets/bfc-utility/src/pallet/mod.rs, pallets/relay-manager/src/lib.rs, pallets/relay-manager/src/pallet/impls.rs, pallets/relay-manager/src/pallet/mod.rs, primitives/bfc-staking/Cargo.toml, primitives/bfc-staking/src/lib.rs, runtime/dev/src/lib.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs, tests/package-lock.json, tests/package.json, tools/package-lock.json, tools/package.json
- Merge final version of v1.2.5 to the main branch
=> Release v1.2.5

Cargo.lock, Cargo.toml, runtime/dev/src/lib.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- patch `rust-evm`
- regenerate lock file (apply frontier patch)
- increase runtime versions
- https://github.com/bifrost-platform/bifrost-frontier/pull/10
- https://github.com/bifrost-platform/evm/pull/1
=> NODE-86, deps: patch rust-evm

Cargo.lock, node/common/src/rpc.rs, node/core/src/command.rs, node/dev/src/rpc.rs, node/dev/src/service.rs, node/mainnet/src/rpc.rs, node/mainnet/src/service.rs, node/testnet/src/rpc.rs, node/testnet/src/service.rs, tests/package-lock.json
https://github.com/bifrost-platform/bifrost-frontier/pull/12
=> NODE-84, chore: web3_clientVersion response format

tests/commands/set_node.ts
- update test commands to let it work
=> test: update test commands

pallets/bfc-staking/src/lib.rs, pallets/bfc-staking/src/pallet/impls.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> NODE-103, hotfix: staking update

pallets/bfc-offences/src/migrations.rs, pallets/bfc-offences/src/pallet/mod.rs, pallets/bfc-staking/src/migrations.rs, pallets/bfc-utility/src/migrations.rs, pallets/bfc-utility/src/pallet/mod.rs, pallets/relay-manager/src/migrations.rs
- Add pallet version migrations for `pallet_bfc_utiltity` & `pallet_bfc_offences` (mainnet only)
- Set pallets to skip previous version upgrades
=> deps: match pallet versions

node/dev/src/chain_spec.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-registration-pool/src/weights.rs, tests/tests/pallets/test_btc_registration_pool.ts
- add `clear_vault()` extrinsic
=> NODE-109, feat: registration pool update

pallets/btc-registration-pool/src/pallet/impls.rs, primitives/multi-sig/src/traits.rs
=> NODE-110, fix: use correct vault address

pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-socket-queue/src/lib.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, pallets/btc-socket-queue/src/weights.rs, primitives/multi-sig/src/traits.rs
- update `UnsignedPsbtMessage`
- check `ServiceState`
=> NODE-119, unsigned psbt message update

Dockerfile, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs
- Add sudo-only multisig set extrinsic
- Use correct socket message duplication check
- Change position output can not always exist
=> minor fixes

pallets/btc-socket-queue/src/pallet/mod.rs
=> chore: update ensure

pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs
- Emit PSBT Txid on `RollbackPsbtSubmitted` event
- Update `try_psbt_output_verification()`
=> fix: socket queue minor update

pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs
- Use `SetOrigin` on `submit_rollback_request()` only
=> fix: update access control

node/dev/src/chain_spec.rs, runtime/dev/src/lib.rs, tests/package-lock.json, tests/package.json, tests/tests/pallets/test_btc_registration_pool.ts, tests/tests/pallets/test_btc_socket_queue.ts, tests/tests/providers.ts, tests/tests/set_dev_node.ts, tests/tests/transactions.ts, tools/package-lock.json
=> NODE-120, test code update

Cargo.lock, pallets/btc-registration-pool/Cargo.toml, pallets/btc-socket-queue/Cargo.toml, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs, runtime/testnet/src/lib.rs
* add psbt fee verification logic
=> NODE-127, fix: add psbt fee verification logic

Cargo.lock, pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/lib.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, precompiles/btc-registration-pool/Cargo.toml, precompiles/btc-registration-pool/src/lib.rs, precompiles/btc-socket-queue/Cargo.toml, precompiles/btc-socket-queue/src/lib.rs, runtime/dev/src/lib.rs, runtime/testnet/src/lib.rs
- Migrate unsigned transactions to unpayable extrinsics
=> NODE-130, fix: Update to unpayable extrinsics

pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs, runtime/testnet/src/lib.rs, tests/tests/pallets/test_btc_registration_pool.ts, tests/tests/pallets/test_btc_socket_queue.ts
Reverts bifrost-platform/bifrost-node#73
=> Revert "fix: replace to `ensure_signed`"

Cargo.lock, pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/lib.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, precompiles/btc-registration-pool/Cargo.toml, precompiles/btc-registration-pool/src/lib.rs, precompiles/btc-socket-queue/Cargo.toml, precompiles/btc-socket-queue/src/lib.rs, runtime/dev/src/lib.rs, runtime/testnet/src/lib.rs
Reverts bifrost-platform/bifrost-node#72
=> Revert "NODE-130, fix: Update to unpayable extrinsics"

pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/lib.rs, pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs
=> NODE-131, fix: add verifiers to signature

pallets/btc-registration-pool/src/pallet/mod.rs, runtime/dev/src/lib.rs
=> NODE-128, fix: use correct service state check

pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs
- `submit_bump_fee_request()`: Submit an unsigned PSBT to Replace-by-Fee (RBF) a pending outbound transaction.
=> NODE-134, feat: add `submit_bump_fee_request()`

pallets/btc-socket-queue/src/pallet/impls.rs
Fix fee rate calculation for the size difference between the unsigned and signed PSBT.
This ensures the fee rate limit is checked against the estimated final transaction size after signatures, preventing premature failures during unsigned PSBT submission.
=> NODE-135, fix: estimate size of finalized psbt's tx for fee verification

pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/mod.rs, primitives/multi-sig/src/traits.rs
- only permit when the migration tx broadcast
=> NODE-139, fix: only permit when the migration tx broadcast

pallets/btc-socket-queue/src/pallet/mod.rs
* include field `is_approved` into signature message. (fn submit_rollback_poll())
=> NODE-141, fix: include field `is_approved` into signature message

pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/btc-socket-queue/src/pallet/mod.rs, precompiles/btc-registration-pool/src/interface.sol, precompiles/btc-registration-pool/src/lib.rs, primitives/multi-sig/src/traits.rs
- apply pending and approval process when setting refunds
=> NODE-142, refactor: apply pending and approval process when setting refunds

pallets/btc-socket-queue/src/pallet/mod.rs, runtime/dev/src/lib.rs
=> feat: add `drop_pending_rollback_request`

Cargo.lock, pallets/btc-registration-pool/Cargo.toml, pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-registration-pool/src/pallet/mod.rs
- add `deadline` to payload and signature
- add `SetRefundsApproval` domain to signature
- check `BondedVault`
=> Improve `approve_set_refunds()`

pallets/bfc-staking/src/migrations.rs, pallets/bfc-staking/src/pallet/mod.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- Add migration code for nomination slot size increment
=> NODE-133, feat: impl nomination slot increment migration code

runtime/mainnet/src/lib.rs
=> chore: remove passed storage migration

Cargo.lock, pallets/btc-registration-pool/src/lib.rs, pallets/btc-registration-pool/src/pallet/impls.rs, pallets/btc-socket-queue/src/lib.rs, pallets/btc-socket-queue/src/pallet/impls.rs, pallets/relay-manager/Cargo.toml, pallets/relay-manager/src/pallet/impls.rs, pallets/relay-manager/src/pallet/mod.rs, primitives/btc-relay/src/lib.rs, primitives/btc-relay/src/traits.rs, runtime/dev/src/lib.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
- 릴레이어 주소 변경 시, BRP pallet (SocketQueue, RegistrationPool)들의 일부 스토리지 업데이트
=> NODE-150, feat: handle relayer set updates

runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> deps: update runtime version

precompiles/btc-registration-pool/src/lib.rs, runtime/mainnet/src/lib.rs
=> cherry-pick: include system vault address

precompiles/btc-registration-pool/src/lib.rs, runtime/mainnet/src/lib.rs
=> (rollback) cherry-pick: include system vault address

pallets/relay-manager/src/pallet/impls.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> fix: update MembershipChanged

precompiles/bfc-staking/src/lib.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> NODE-173, fix: overestimated yearly return

pallets/blaze/src/lib.rs, pallets/blaze/src/pallet/impls.rs, pallets/blaze/src/pallet/mod.rs, runtime/dev/src/lib.rs
=> NODE-182, feat: fee rate submission

pallets/blaze/src/lib.rs, pallets/blaze/src/pallet/impls.rs, pallets/blaze/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/impls.rs, primitives/btc-relay/src/traits.rs, runtime/dev/src/lib.rs
=> NODE-181, feat: impl submit_outbound_requests

pallets/blaze/src/lib.rs, pallets/blaze/src/pallet/impls.rs, pallets/blaze/src/pallet/mod.rs, pallets/btc-socket-queue/src/pallet/impls.rs, primitives/btc-relay/src/traits.rs, runtime/dev/src/lib.rs
=> NODE-180, feat: utxo submission

precompiles/bfc-staking/src/interface.sol, precompiles/bfc-staking/src/lib.rs, runtime/mainnet/src/lib.rs, runtime/testnet/src/lib.rs
=> NODE-185, feat: create nominator_estimated_yearly_return function

tests/package.json, tests/tests/precompiles/test_bfc_staking.ts, tools/tsconfig.json
=> fix: correctly use mocha with tsx
